---

- name: Setup Ubuntu WSL with Required Packages and Configuration
  hosts: localhost
  become: yes

  vars_files:
    - vars/setup_vars.yml

  tasks:

    - name: Ensure git is installed
      package:
        name: 'git'
        state: present

    - name: Parse requirements file
      set_fact:
        required_roles: "{{ lookup('file', playbook_dir + '/roles/requirements.yml') | from_yaml }}"

    - name: Clone necessary roles
      git:
        repo: '{{ item.src }}'
        dest: '{{ ansible_roles_path }}/{{ item.name }}'
        version: '{{ item.version }}'
      loop: '{{ required_roles }}'

    - name: Ensure ssh directory exists
      file: 
        path: '{{ ssh_dir_path }}'
        state: directory
        owner: '{{ ubuntu_user }}'
        group: '{{ ubuntu_user }}'
        mode: '0700'

    - name: "Create SSH key-pair for {{ ubuntu_user }}"
      openssh_keypair:
        path: '{{ ssh_key_path }}'
      become_user: '{{ ubuntu_user }}'

    - name: "Edit and validate sudoers for {{ ubuntu_user }}"
      lineinfile:
        path: '{{ sudoers_file_path }}'
        regexp: '^%sudo'
        line: '{{ sudo_nopass_line }}'
        validate: '{{ visudo_path }}'

    - name: Create git aliases
      blockinfile:
        path: '{{ bash_alias_file_path }}'
        block: |
          alias gcl="git clone"
          alias gbr="git branch"
          alias gco="git checkout"
          alias gad="git add --all"
          alias gcm="git commit -m"
          alias gpl="git pull"
          alias gps="git push"
          alias gst="git status"
          alias gstsh="git stash"
          alias ghst='git log --pretty=format:"%h %ad | %s%d [%an]" --graph --date=short'
          alias python="python3"
          alias pip="pip3"
          alias kc="kubectl"
          alias mkb="minikube"
        insertafter: EOF
        create: yes

    - name: Install Java OpenJDK
      include_role: 
        name: ansible-role-java
      vars:
        - java_packages: '{{ openjdk_package }}'
        - java_home: '{{ java_home_path }}'

    - name: Install Terraform
      include_role: 
        name: ansible-role-terraform
      vars:
        - terraform_version: '{{ terraform_install_version }}'
      when: install_iac_tools | bool

    - name: Install Packer
      include_role: 
        name: ansible-role-packer
      vars:
        - packer_version: '{{ packer_install_version }}'
      when: install_iac_tools | bool

    - name: Install Docker CE and Docker Compose
      include_role:
        name: ansible-role-docker
      vars:
        - docker_users: 
            - '{{ docker_sudo_users }}'

    - name: Install Required Python Packages via pip3
      include_role: 
        name: ansible-role-pip
      vars:
        - pip_install_packages: '{{ pip_package_list }}'

    - name: Install AWX Tower
      include_role:
        name: ansible-role-awx
      vars:
        - docker_hub_password: '{{ docker_hub_pass }}'
        - awx_repo_dir: '{{ ubuntu_user_installs }}/awx-tower'
      when: install_devops_tools | bool

    - name: Install Jenkins CI
      include_role:
        name: ansible-role-jenkins_as_docker
      vars:
        - jenkins_admin_user: '{{ jenkins_admin }}'
        - jenkins_admin_password: '{{ jenkins_admin_pass }}'
        - docker_hub_username: '{{ docker_hub_user }}'
        - docker_hub_password: '{{ docker_hub_pass }}'
        - dockerfile_build_path: '{{ ansible_roles_path }}/ansible-role-jenkins_as_docker/files'
        - ubuntu_user_home_path: '{{ ubuntu_user_home }}'
      when: install_devops_tools | bool
    
    - name: Install Artifactory
      include_role:
        name: ansible-role-artifactory_as_docker
      vars:
        - ubuntu_user_home_path: '{{ ubuntu_user_home }}'
      when: install_devops_tools | bool
      
    - name: Install Jupyter Notebook
      include_role:
        name: ansible-role-jupyter_as_docker
      vars:
        - ubuntu_user_home_path: '{{ ubuntu_user_home }}'
      when: install_jupyter_tools | bool

    - name: Install Miniconda
      include_role:
        name: ansible-role-miniconda
      vars:
        - ubuntu_user_home_path: '{{ ubuntu_user_home }}'
      when: install_jupyter_tools | bool

    - name: Setup Nginx to Serve Apps on Localhost
      include_role:
        name: ansible-role-nginx_for_local
      vars:
        - nginx_app_list: '{{ app_list }}'
      when: install_devops_tools | bool

    - name: Install Minikube
      include_role:
        name: ansible-role-minikube
      vars:
        - minikube_user: '{{ ubuntu_user }}'
        - systemctl_script_dir_path: '{{ systemctl_script_path }}'
      when: install_minikube_tools | bool
    
    - name: Check if Zsh and Oh-My-Zsh are installed
      stat:
        path: '{{ ubuntu_user_home }}/.oh-my-zsh'
      register: ohmyzsh

    - name: Setup and Customize Oh-My-Zsh
      include_role:
        name: ansible-role-ohmyzsh
      vars:
        user: '{{ ubuntu_user }}'
        user_home: '{{ ubuntu_user_home }}'
        users_installs_dir: '{{ ubuntu_user_installs }}'
        zsh_theme: '{{ zsh_theme_name }}'
      when: ohmyzsh.stat.exists == false
