---

- name: Setup Ubuntu WSL with Required Packages and Configuration
  hosts: localhost
  become: yes

  vars_files:
    - vars/setup_vars.yml

  tasks: 

    - name: "Create SSH key-pair for {{ ubuntu_user }}"
      openssh_keypair:
        path: '{{ ssh_key_path }}'
      become_user: '{{ ubuntu_user }}'

    - name: "Edit and validate sudoers for {{ ubuntu_user }}"
      lineinfile:
        path: '{{ sudoers_file_path }}'
        regexp: '^%sudo ALL='
        line: '{{ sudo_nopass_line }}'
        validate: '{{ visudo_path }}'

    - name: Install Java OpenJDK
      include_role: 
        name: ansible-role-java
      vars:
        - java_packages: '{{ openjdk_package }}'
        - java_home: '{{ java_home_path }}'

    - name: Install Terraform
      include_role: 
        name: ansible-role-terraform
      vars:
        - terraform_version: '{{ terraform_install_version }}'

    - name: Install Packer
      include_role: 
        name: ansible-role-packer
      vars:
        - packer_version: '{{ packer_install_version }}'

    - name: Install Docker CE and Docker Compose
      include_role:
        name: ansible-role-docker
      vars:
        - docker_users: '{{ docker_sudo_users }}'

    - name: Install Required Python Packages via pip3
      include_role: 
        name: ansible-role-pip
      vars:
        - pip_install_packages: '{{ pip_package_list }}'

    - name: Install AWX Tower
      include_role:
        name: ansible-role-awx
      vars:
        - docker_hub_password: '{{ docker_hub_pass }}'

    - name: Install Jenkins CI
      include_role:
        name: ansible-role-jenkins_as_docker
      vars:
       - jenkins_admin_user: '{{ jenkins_admin }}'
       - jenkins_admin_password: '{{ jenkins_admin_pass }}'
       - docker_hub_username: '{{ docker_hub_user }}'
       - docker_hub_password: '{{ docker_hub_pass }}'

    - name: Setup Nginx to Serve Apps on Localhost
      include_role:
        name: ansible-role-nginx_for_local
      vars:
        - nginx_app_list: '{{ app_list }}'

    - name: Install Zsh on Ubuntu
      package: 
        name: zsh
        state: latest
      
    - name: Install Oh-My-Zsh Terminal
      command: 'echo {{ jenkins_admin_pass }} | sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"'
      become_user: '{{ ubuntu_user }}'

    - name: Set Custom Oh-My-Zsh Theme
      lineinfile:
        path: '{{ zshrc_file_path }}'
        regexp: '^ZSH_THEME='
        line: 'ZSH_THEME=""{{ zsh_theme_name }}""'
      notify: reload zshrc

  handlers:

    - name: reload zshrc
      command: 'source {{ zshrc_file_path }}'